FROM debian:testing

RUN apt-get update -y && apt-get install -y \
    r-base-dev libcurl4-openssl-dev libssl-dev libgdal-dev libgeos-dev libproj-dev \
    libopencv-dev libtesseract-dev tesseract-ocr-eng libmagick++-dev libprotobuf-dev \
    protobuf-compiler libgit2-dev libxml2-dev libudunits2-dev libpoppler-cpp-dev \
    libsodium-dev libjq-dev libicu-dev libavfilter-dev cargo
